### PR TITLE
changed to document since window took a long time to load

### PR DESCRIPTION
**Pull request by FredrikAugust**

### CODE REVIEW

**Comment by NateBrune** [comment]
Good idea.

**Comment by NateBrune** [comment]
Fyi, this isn't live yet, I need a computer, I'm on my phone :/

**Comment by FredrikAugust** [comment]
That sucks.. :( Tell me og you need help with anything then

**Comment by NateBrune** [comment]
Fyi it is live now :)

**Comment by FredrikAugust** [comment]
Working?

**Comment by NateBrune** [comment]
It works...

**Comment by FredrikAugust** [comment]
That's because I set a timeout on it, feel free to reduce it. Hard to
optimize when it's not my code :)

lør. 11. jul. 2015 kl. 20.41 skrev Nate Brune notifications@github.com:

**Comment by NateBrune** [comment]
Yeah I'm sorry I edited it because I didnt want to seem rude. Its fine thank you.

**Comment by FredrikAugust** [comment]
No problem :smile:

**Pull request merged**
