### PR TITLE
Added basic server pinging

### PR DESCRIPTION
**Pull request by n17r4m**
Shows a ping with response time for each server listed. Shows (down) if server is not able to be pinged.

Does the ping by trying to make a  request. seems to work!

### CODE REVIEW

**Comment by NateBrune** [comment]
aw hell yeah man I love it! Im gonna merge this because its pretty badass. I think I am going to add a new column for ping though. Thank you man, this is the first time anyone has ever forked one of my repos, awesome!

**Comment by NateBrune** [comment]
Wow, I cant believe I literally forgot to merge after that... cheers!

**Comment by n17r4m** [comment]
No worries at all! not sure if changes will need to be pushed up to the site by hand because of how you are storing the data, but I'll leave that delicate surgery to you. :)

**Comment by NateBrune** [comment]
Yeah I know, I decided that adding another column was going to take too long (because of how stupidly I am storing the data) so I changed the date added field. This way I think is actually better. Now when you click export you get the time data which you might want, and when you are just looking at it you get the ping data which changes invariably so you wouldn't want to export that. Thanks.

**Pull request merged**
